### PR TITLE
Some fixes + fixes from decimad's repo

### PR DESCRIPTION
**Pull request by Wohlstand**

### CODE REVIEW

**Comment by ltjax** [comment]
Any reason why you would want to undo removing the unnamed-namespace from the header? That's just terrible style that way, and it pollutes all the object files it gets used in. Is something not working with the extern variant? 

Honestly, I see the point for the changes in native_converter and call_function, but the rest does not look good.

**Comment by Wohlstand** [comment]
oops, I did that accidentally while merged conflicts, missed that up, sorry, will fix that

**Comment by ltjax** [comment]
Ok, great - did the same thing happen to the pop_back meta function? iirc, it was not even used, so I removed it.

**Comment by Wohlstand** [comment]
Okay, I just removed junk code and fixed that

**Pull request merged**
